CREATE TABLE Users (
	login VARCHAR(20) DEFAULT NULL,
	password VARCHAR(20) DEFAULT NULL,
	PRIMARY KEY (login)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE Notes (
	id INTEGER,	
	publisher VARCHAR(20) DEFAULT NULL,
	reader VARCHAR(20) DEFAULT NULL,
	note VARCHAR(255) DEFAULT NULL,
	FOREIGN KEY (publisher) REFERENCES Users (login),
	FOREIGN KEY (reader) REFERENCES Users (login)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
